{
 "title": "Core-metrics-monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "API_Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apiserver_request_latencies_summary"
    }
   ]
  },
  {
   "title": "NODE_IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_disk_io_now" }
   ]
  },
  {
   "title": "Container_CPU_Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "container_cpu_load_average_10s" }
   ]
  }
 ]
}